name: coupled_channel
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - numba
  - scipy
  - scikit-learn 
  - netcdf4
  - matplotlib